title: Basketball Teaching Points
theme: minima

# Add navigation
header_pages:
  - teaching-points.md


  # Set to `true` to show excerpts on the homepage.
show_excerpts: true

footer:
  location:  Melbourne Australia
