title: Basketball Teaching Points - v1
theme: minima

# Add navigation
header_pages:
  - bos_short_into_pistols.md
  - bos_short_into_pistols copy.md
  - bds_arrows_press.md
  - bs1.md
  - test.md
  - videos.md
  - v1_bos_short_into_pistols.md
  

footer:
  location:  Melbourne Australia
