title: Basketball Teaching Points
theme: minima

# Add navigation
header_pages:
  - concepts.html
  - teaching-points.md
  - practice/index_v2.md
  - blog.html

include:
  - assets/css/custom.css
  # Set to `true` to show excerpts on the homepage.
show_excerpts: true



footer:
  location:  Melbourne Australia
